"""22

Revision ID: 73d1d874cb2b
Revises: fe5de8e3bd24
Create Date: 2024-06-14 08:21:02.283215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73d1d874cb2b'
down_revision = 'fe5de8e3bd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tugas', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tugas', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.String(length=50),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
