"""Initial migration.

Revision ID: 8e72d3f8459c
Revises: 7583c72f04ca
Create Date: 2024-06-05 15:05:29.003987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e72d3f8459c'
down_revision = '7583c72f04ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('tugas', schema=None) as batch_op:
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('deskripsi',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('deadline',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('kategori',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tugas', schema=None) as batch_op:
        batch_op.alter_column('kategori',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('deadline',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('deskripsi',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('nama',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    op.drop_table('account')
    # ### end Alembic commands ###
